setwd("~/Desktop/Evolution/Tasks/Task_02")
beren3<-read.csv("beren_new.csv")
unique(beren3$event)
Diaper<-which(beren3[,9] == "wet")
beren3Diaper<-beren3[Diaper,]
(beren3Diaper)
Diaper<-which(beren3$event == "wet")
avgDiaper<-mean(beren3$value[Diaper])
avgDiaper<-tapply(beren3$value[Diaper], beren3$day[Diaper], mean)
varDiaper<-tapply(beren3$value[Diaper], beren3$day[Diaper], var)
totalDiaper<-tapply(beren3$value[Diaper], beren3$day[Diaper], sum)
numDiaper<-tapply(beren3$value[Diaper], beren3$day[Diaper], length)
cor(beren3$value[Diaper], beren3$day[Diaper])
cor.test(beren3$value[Diaper], beren3$day)
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalDiaper)), totalDiaper, type="b", pch=16, xlab="day", ylab="Diaper")
abline(h=avgDiapers lty=2, col='red')
pdf("r02c-totalDiapersPerDay.pdf", height=4, width=4)
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalDiaper)), totalDiaper, type="b", pch=16, xlab="day", ylab="Diaper")
abline(h=avgDiapers lty=2, col='red')
dev.off()

# I'm predicting that he will use an average of 5 wet diapers per day next week